#!/usr/bin/env bash

# DMM LIB PATH
LIB=$PWD/libft_malloc.so
# INJECT
export LD_PRELOAD=$LIB
# TO USE SHOW_ALLOC_MEM
export LD_LIBRARY_PATH=$PWD

# START COMMAND IN ARGUMENT
echo Starting: "$@"
/usr/bin/time -f "mem_max=%M time=%E" "$@"
